### ISSUE TITLE
Test failure during debian package build

### ISSUE THREAD

**Issue by picca** [vasole/fisx#13]
Hello armando

here the result of the unit tests

testXRFImport (fisx.tests.testXRF.testXRF) ... ok
testXRFInstantiation (fisx.tests.testXRF.testXRF) ... ok
testXRFResults (fisx.tests.testXRF.testXRF) ... ERROR
testEPDL97Import (fisx.tests.testEPDL97.testEPDL97) ... ok
testElementsImport (fisx.tests.testElements.testElements) ... ok
testElementsInstantiation (fisx.tests.testElements.testElements) ... FAIL
testSimpleSpecfileImport (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReading (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReadingCompatibleWithUserLocale (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReadingWithCRLF (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testDataDirectoryPresence (fisx.tests.testDataDir.testDataDir) ... FAIL
testDataFilePresence (fisx.tests.testDataDir.testDataDir) ... FAIL
testDocDirectoryPresence (fisx.tests.testDataDir.testDataDir) ... FAIL
# 
## ERROR: testXRFResults (fisx.tests.testXRF.testXRF)

Traceback (most recent call last):
  File "fisx/tests/testXRF.py", line 89, in testXRFResults
    elementsInstance = Elements()
  File "python/cython/_fisx.pyx", line 276, in fisx._fisx.PyElements.__cinit__ (/<<PKGBUILDDIR>>/python/cython/_fisx.cpp:4950)
  File "fisx/DataDir.py", line 60, in <module>
    raise IOError('%s directory not found' % basename)
IOError:  directory not found
# 
## FAIL: testElementsInstantiation (fisx.tests.testElements.testElements)

Traceback (most recent call last):
  File "fisx/tests/testElements.py", line 81, in testElementsInstantiation
    'Unsuccesful Elements() instantiation')
AssertionError: Unsuccesful Elements() instantiation
# 
## FAIL: testDataDirectoryPresence (fisx.tests.testDataDir.testDataDir)

Traceback (most recent call last):
  File "fisx/tests/testDataDir.py", line 69, in testDataDirectoryPresence
    'Unsuccessful fisx.DataDir import')
AssertionError: Unsuccessful fisx.DataDir import
# 
## FAIL: testDataFilePresence (fisx.tests.testDataDir.testDataDir)

Traceback (most recent call last):
  File "fisx/tests/testDataDir.py", line 79, in testDataFilePresence
    self.testDataDirectoryPresence()
  File "fisx/tests/testDataDir.py", line 69, in testDataDirectoryPresence
    'Unsuccessful fisx.DataDir import')
AssertionError: Unsuccessful fisx.DataDir import
# 
## FAIL: testDocDirectoryPresence (fisx.tests.testDataDir.testDataDir)

Traceback (most recent call last):
  File "fisx/tests/testDataDir.py", line 104, in testDocDirectoryPresence
    'Unsuccessful fisx.DataDir import')
AssertionError: Unsuccessful fisx.DataDir import

---

Ran 13 tests in 0.070s

FAILED (failures=4, errors=1)
('Instantiation error: ', <type 'exceptions.IOError'>, IOError(' directory not found',), <traceback object at 0xb6b7357c>)
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: cd /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_2.7/build; python2.7 -m unittest discover -v 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
debian/rules:11: recipe for target 'build' failed
make: **\* [build] Error 25
dpkg-buildpackage: error: debian/rules build gave error exit status 2

It seems that fisx does not find the DATADIR. Indeed I fixed it for the package once installed.
export FISX_DATA_DIR=/usr/share/fisx/
This way I can share the data (18 Mo) between the python2 and python3.

I do not have yet a great conviction how to deal with this issue...
I can use your tests in the ci.Debian.net (test pacakges once they are installed), but not during the build process.

**Comment by vasole** [comment]
Hi Fred,

Typically I install fisx and only then I run the tests via python -m 
fisx.tests.testAll as specified in the README (shown at 
https://github.com/vasole/fisx/)

The whole purpose of those tests is to test if the code will work once 
installed. One can build the library, test it for the build and then 
once installed, if the data are not at the same place, it will not work 
despite having passed the tests during the build process.

Nevertheless I tried to allow the testing during the build too in 
DataDir.py, but somehow it does not find the data. Where does the build 
happen?

You should not need to "fix" the code once installed if you set the 
environment variable prior to the build, because then the module should 
look for the data there.

As you see, the setup.py contains the lines:

#for the time being there is no doc directory
FISX_DATA_DIR = os.getenv("FISX_DATA_DIR")
FISX_DOC_DIR = os.getenv("FISX_DOC_DIR")

in order to allow you to specify where the data are expected to be found 
on the installed module. If you set the both environment variables to 
/usr/share/fisx/ prior to the build, you should not need to do anything 
on the installed modules.

Does that help?

Armando

**Comment by picca** [comment]
I will create the test once installed for python2 and python3

An I will use the test during the build with a modifyed FISX_DATA_DIR only for these tests.

thanks, armando

Fred

**Comment by picca** [comment]
Hello Armando

I test a few things , here what I understood fromthe build and install process.

the setup.py check if the env variable FISX_DATA_DIr exist and replace it by
fisx/fisx_data if the env is not present.

these DATA are copyied only during the install phase of the build process.
so I end up with fisx_data in the python modules.

I have two copy of the data, one for python2 and one for python3.

If I want to put the data in one place, I need to
export FISX_DATA_DIR=/usr/share/fisx

and then move around the data in order to put them in the python-fisx-common package

export WITH_CYTHON=1
export FISX_DATA_DIR=/usr/share/fisx/
export PKGCOMMON=$(CURDIR)/debian/python-fisx-common/

export PYBUILD_NAME=fisx
export PYBUILD_AFTER_INSTALL_python2=dh_numpy ;\
        rm -rf {destdir}$(FISX_DATA_DIR)
export PYBUILD_AFTER_INSTALL_python3=dh_numpy3 ;\
        mkdir -p $(PKGCOMMON)/usr/share ;\
        mv {destdir}$(FISX_DATA_DIR) $(PKGCOMMON)/usr/share

override_dh_clean:
        dh_clean
        rm -rf python/fisx.egg-info/

%:
        dh $@ --with python2,python3 --buildsystem=pybuild

now during the test I have an error.
the problem is that the env variable is not use as the default during the test
Usually env variable superseed other configuration.
This is not the case in your Datadir.py

You should use the env of fallback to the default.
thsi would simplify the datadir.py 

why don't you use pyxdg for all your packages.
the semantic is well known. :)

cheers

Fred

**Comment by picca** [comment]
Is it possible also to standardize the tests like this

import fisx
fisx.tests()

like for numpy, scipy, pyFAI, etc...

It woule simplify the CI integration in debian.

**Comment by vasole** [comment]
Hi Fred,

In my first reply I said:

Nevertheless I tried to allow the testing during the build too in DataDir.py, but somehow it does not find the data. Where does the build happen?

I have just corrected a bug preventing that functionality from working (your basename was different from fisx_data). Now DataDir.py should be able to find the data from inside the ./build/lib.xxxx directory. So going to ./build/lib.xxxx and running python -m fisx.tests.testAll from there should work now even if at installation the data will go to your specified place.

Armando

**Comment by picca** [comment]
> Hi Fred,

Hello armando

> In my first reply I said:
> 
> Nevertheless I tried to allow the testing during the build too in DataDir.py, but somehow it does not find the data. Where does the build happen?

Yes this is why I think that the right way to fix tis issue is to invert the logic in Datadir.py
env var takes precedence over hard coded values :)

Cheers

Fred

**Comment by vasole** [comment]
But the environment variable was thought to be used to set the final destination. If you would want to test things via that way, you would have to set the destination environment variable, perform the build, change the environment variable, perform the tests, get rid of the environment variable and build the package. Now that DataDir.py works as it was supposed to do, you only set the environment variable  to set the destination and the tests will run from the build directory as far is it is somewhere down the directory where setup.py is.

I thought Debian was against the use of environment variables. I remember I had to change things in the past in order to avoid that. If it is no longer the case, it costs me nothing to check for the existence of the environment variables at run time.

**Comment by picca** [comment]
> �But the environment variable was thought to be used to set the final destination. If you would want to test things using via that way, you would have to set the destination environment variable, perform the build, change the environment variable, > perform the tests, get rid of the environment variable and build the package. Now that DataDir.py works as it was supposed to do, you only set the environment variable to set the destination and the tests will run from the build directory as far is it  somewhere down the directory where setup.py is.

If I remember correctly this environment variable was used in order to put the right path into the DataDir.py during the python setup.py build
in fact Debian use the --root option in order to build the packge. so the default build directory is not the one use during the build process.

so the easyer is effectively to set the env during thei build phase
and then change it only for the test phase.

Once installed there is no more env. so it is ok.

> I thought Debian was against the use of environment variables. I remember I had to change things in the past in order to avoid that. If it is no longer the case, it costs me nothing to check for the existence of the environment variables at run time.

by default the software should work without env. (Datadir.py is ok with the right path :).
BUt if the user set a different FISX_DATA_DIR, it should use it.

so to my opinion

export FISX_DATa_DIR=/usr/share/fisx
python setup.py build -> geerate the right Datadir.py once installed
export FISX_DATA_DIR=./fisx_data
python setup.py test

because during the test process the Datadir.py (path for installation) is not available.

What do you think.

You should have something as simple as this in all your packages.

on Debian I compile for 4 differentes interpreter, this is why I share the common part.

ptyhon2, python2-dbg, python3, pyhton3-dbg and in the near futur pypy

**Comment by vasole** [comment]
I can add the environmental variable option to DataDir.py AFTER the test for the hard coded. That will make sure that the use of the environmental variable is only used for testing during build. I remind you passing the tests during the build will not warrant things will work once installed.

**Comment by vasole** [comment]
Done. It will take FISX_DATA_DIR from the environment if the hard coded path is not available. That will be made at user's own risk.

**Comment by picca** [comment]
why not this one line

FISX_DATA_DIR = os.getenv('FISX_DATA_DIR') or 'DATA_DIR_FROM_SETUP'

and that's all

**Comment by vasole** [comment]
Because I do not want to give priority to the environment variable.

If I change the data files and the user still has a previous installation somewhere set with an environment variable results can be wrong.

**Comment by vasole** [comment]
Can this be closed?

**Comment by picca** [comment]
can you do a release with this in order to close it ?

---

De : V. Armando Sol� [notifications@github.com]
Envoy� : mardi 21 juin 2016 12:23
� : vasole/fisx
Cc : PICCA Frederic-Emmanuel; Author
Objet : Re: [vasole/fisx] Test failure during debian package build (#13)

Can this be closed?

�

**Comment by vasole** [comment]
On 21/06/2016 12:52, picca wrote:

> can you do a release with this in order to close it ?
> I have prepared the things but we have to wait for the answer from NIST 
> concerning the use of data generated using their XCOM database. Perhaps 
> they want me to add something particular to the header of the file.

Armando
