### ISSUE TITLE
Licenses of the fisx_data files

### ISSUE THREAD

**Issue by picca** [vasole/fisx#14]
Hello, could you add the licenses of all the fisx_data files.
In order to upload fisx into Debian, I need to check the licenses of these files.
Depending on these licnese, I will target the main, non-free or no upload into Debian.

I need the full licenses text of the original databases used to generate these files.
without these informations, I could not upload fisx into Debian :((

Cheers

**Comment by vasole** [comment]
I am going to ask, but data are not bound to copyright and, even if the free databases from where I extracted/generated them can be copyrighted, the data themselves are not.

See for instance:

http://www.lib.umich.edu/copyright/facts-and-data

**Comment by vasole** [comment]
For instance, concerning XCOM data, the database:

https://catalog.data.gov/dataset/nist-xcom-photon-cross-sections-database-srd-8

points to the license:

http://www.nist.gov/open/license.cfm

Where there seems to be a distinction between the data themselves and the compilation.

**Comment by picca** [comment]
Hello 

I need the licenses of all these files and there copyright if releant.

Files: fisx_data/BindingEnergies.dat
       fisx_data/LShellConstants.dat
       fisx_data/LShellRates.dat
       fisx_data/MShellConstants.dat
       fisx_data/MShellRates.dat
       fisx_data/KShellConstants.dat
       fisx_data/KShellRates.dat
Copyright: ???
License: ???

Cheers

**Comment by vasole** [comment]
Hi Fred,

I was expecting potential problems for the other files (EPDL97, EADL and 
XCOM) that were extracted from free databases.

The files you mention if I am not mistaken (I am going to verify) were 
typed in by myself from published tables in the literature in some 
cases, interpolated from published data in other cases and using 
published formulas in yet other cases. I will try to add a header with 
the references of the published data.

Armando

**Comment by picca** [comment]
Hello Armando

> I was expecting potential problems for the other files (EPDL97, EADL and
> XCOM) that were extracted from free databases.

I sent an email to debian-legal for the xcom data. we will see.

> The files you mention if I am not mistaken (I am going to verify) were
> typed in by myself from published tables in the literature in some
> cases, interpolated from published data in other cases and using
> published formulas in yet other cases. I will try to add a header with
> the references of the published data.

thanks for your efforts.
This is really important to think about the data policy. If the esrf think to change this it could be interesting to let debian-legal gives there point of view in order to produce something 
DFSG-free for the futur. This would simplify the distribution of our softwares.

data matters.

Fred

**Comment by vasole** [comment]
I have added the references of the sources of the files, in particular to those created by myself from published articles. The article references and details about the operations performed are provided.
