### ISSUE TITLE
unit test failure with python3

### ISSUE THREAD

**Issue by picca** [vasole/fisx#15]
Hello armando, it works great with the python2 versions but with python3 I get this

Cheers

Fred

I: pybuild base:184: cd /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v 
testDataDirectoryPresence (fisx.tests.testDataDir.testDataDir) ... ok
testDataFilePresence (fisx.tests.testDataDir.testDataDir) ... FAIL
testDocDirectoryPresence (fisx.tests.testDataDir.testDataDir) ... ok
testEPDL97Import (fisx.tests.testEPDL97.testEPDL97) ... ok
testElementsImport (fisx.tests.testElements.testElements) ... ok
testElementsInstantiation (fisx.tests.testElements.testElements) ... FAIL
testSimpleSpecfileImport (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReading (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReadingCompatibleWithUserLocale (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testSimpleSpecfileReadingWithCRLF (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
testXRFImport (fisx.tests.testXRF.testXRF) ... ok
testXRFInstantiation (fisx.tests.testXRF.testXRF) ... ok
testXRFResults (fisx.tests.testXRF.testXRF) ... ERROR
# 
## ERROR: testXRFResults (fisx.tests.testXRF.testXRF)

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/fisx/tests/testXRF.py", line 89, in testXRFResults
    elementsInstance = Elements()
  File "python/cython/_fisx.pyx", line 288, in fisx._fisx.PyElements.__cinit__ (/<<PKGBUILDDIR>>/python/cython/_fisx.cpp:5192)
OSError: EPDL97: Number of scans not equal one in binding energies file /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build///EADL97_BindingEnergies.dat: iostream error
# 
## FAIL: testDataFilePresence (fisx.tests.testDataDir.testDataDir)

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/fisx/tests/testDataDir.py", line 98, in testDataFilePresence
    'File "%s" does not exist.' % actualName)
AssertionError: False is not true : File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/BindingEnergies.dat" does not exist.
# 
## FAIL: testElementsInstantiation (fisx.tests.testElements.testElements)

Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/fisx/tests/testElements.py", line 81, in testElementsInstantiation
    'Unsuccesful Elements() instantiation')
AssertionError: False is not true : Unsuccesful Elements() instantiation

---

Ran 13 tests in 0.095s

FAILED (failures=2, errors=1)
Instantiation error:  <class 'OSError'> EPDL97: Number of scans not equal one in binding energies file /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build///EADL97_BindingEnergies.dat: iostream error <traceback object at 0xb5f99fcc>
E: pybuild pybuild:274: test: plugin distutils failed with: exit code=1: cd /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build; python3.5 -m unittest discover -v 
dh_auto_test: pybuild --test -i python{version} -p 3.5 returned exit code 13
debian/rules:26: recipe for target 'override_dh_auto_test' failed
make[1]: **\* [override_dh_auto_test] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:14: recipe for target 'build' failed
make: **\* [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by vasole** [comment]
It does not find a file. Is it there or not, where do you put it?

AssertionError: False is not true : File 
"/<>/.pybuild/pythonX.Y_3.5/build/BindingEnergies.dat" does not exist.

Does it work if you run the test once installed? I know you want to do 
it during the build phase too, but it is to check if the problem is on 
your environmental variable.

Armando

**Comment by picca** [comment]
In fact it works with the python2 version. So I think thaht this is a python2/python3 issue.

I set the FISX_DATA_DIR to be fisx_data So it should find all the files distributed with fisx.

**Comment by vasole** [comment]
The DataDirectoryPresence passes but the testDataFilePresence does not pass.
I do not see a Python2/Python3 problem there. That can only happen if the Data directory does not contain the data:

```
def testDataDirectoryPresence(self):
    self.assertTrue(self._importSuccess,
                    'Unsuccessful fisx.DataDir import')
    self.assertTrue(self.dataDir is not None,
                    'Unassigned fisx.DataDir.FISX_DATA_DIR')
    self.assertTrue(os.path.exists(self.dataDir),
                    'Directory "%s" does not exist' % self.dataDir)
    self.assertTrue(os.path.isdir(self.dataDir),
                    '"%s" expected to be a directory' % self.dataDir)

def testDataFilePresence(self):
    # Testing file presence
    self.testDataDirectoryPresence()
    for fname in ['BindingEnergies.dat',
                  'EADL97_BindingEnergies.dat',
                  'EADL97_KShellConstants.dat',
                  'EADL97_KShellNonradiativeRates.dat',
                  'EADL97_KShellRadiativeRates.dat',
                  'EADL97_LShellConstants.dat',
                  'EADL97_LShellNonradiativeRates.dat',
                  'EADL97_LShellRadiativeRates.dat',
                  'EADL97_MShellConstants.dat',
                  'EADL97_MShellNonradiativeRates.dat',
                  'EADL97_MShellRadiativeRates.dat',
                  'EPDL97_CrossSections.dat',
                  'KShellRates.dat',
                  'LShellRates.dat',
                  'MShellRates.dat',
                  'XCOM_CrossSections.dat']:
        actualName = os.path.join(self.dataDir, fname)
        self.assertTrue(os.path.exists(actualName),
                        'File "%s" does not exist.' % actualName)
        self.assertTrue(os.path.isfile(actualName),
                        'File "%s" is not an actual file.' % actualName)
```

**Comment by picca** [comment]
HelloArmando

$ FISX_DATA_DIR=/home/picca/Debian/python-fisx/python-fisx/fisx_data/ python2.7 -c "import DataDir; DataDir.FISX_DATA_DIR"
WARNING: Taking FISX_DATA_DIR from environement.
Use it at your own risk.
$ FISX_DATA_DIR=/home/picca/Debian/python-fisx/python-fisx/fisx_data/ python3.5 -c "import DataDir; DataDir.FISX_DATA_DIR"

so there is definitively something different bitween python2 and python3

**Comment by picca** [comment]
python3: /home/picca/Debian/python-fisx/python-fisx/python/fisx
python2: /home/picca/Debian/python-fisx/python-fisx/fisx_data/

**Comment by picca** [comment]
I instrumented a bit the code and I found this

picca@mordor:~/Debian/python-fisx/python-fisx/python/fisx$ FISX_DATA_DIR=/home/picca/Debian/python-fisx/python-fisx/fisx_data/ python2.7 -c "import DataDir; DataDir.FISX_DATA_DIR; print(DataDir.FISX_DATA_DIR)"
frozen
before: /usr/share/fisx
False
tmp_dir: 
basename: /usr/share/fisx
after/before: fisx/fisx
build
after/before: /fisx/fisx_data
env
WARNING: Taking FISX_DATA_DIR from environement.
Use it at your own risk.
after: /home/picca/Debian/python-fisx/python-fisx/fisx_data/
/home/picca/Debian/python-fisx/python-fisx/fisx_data/
picca@mordor:~/Debian/python-fisx/python-fisx/python/fisx$ FISX_DATA_DIR=/home/picca/Debian/python-fisx/python-fisx/fisx_data/ python3.5 -c "import DataDir; DataDir.FISX_DATA_DIR; print(DataDir.FISX_DATA_DIR)"
frozen
before: /usr/share/fisx
False
tmp_dir: /home/picca/Debian/python-fisx/python-fisx/python/fisx
basename: /usr/share/fisx
after/before: /home/picca/Debian/python-fisx/python-fisx/python/fisx
build
after/before: /home/picca/Debian/python-fisx/python-fisx/python/fisx
env
after: /home/picca/Debian/python-fisx/python-fisx/python/fisx
/home/picca/Debian/python-fisx/python-fisx/python/fisx

as you can see the tmp_dir is different between python2 and python3
it comes from here

```
tmp_dir = os.path.dirname(__file__)
```

https://stackoverflow.com/questions/7116889/python-file-attribute-absolute-or-relative

**Comment by vasole** [comment]
Does it improve if you change

tmp_dir = os.path.dirname(**file**) 

by

 tmp_dir = os.path.dirname(os.path.abspath(**file**))

**Comment by picca** [comment]
> tmp_dir = os.path.dirname(file)
> 
> by
> 
> tmp_dir = os.path.dirname(os.path.abspath(file))

yes and no
If I run this from the source directory, I get this directory for the data

/home/picca/Debian/python-fisx/python-fisx/python/fisx

BUT this is wrong the data are there in the source directory

/home/picca/Debian/python-fisx/python-fisx/fisx_data

the good poin tis that both version now return the same result.
It doesn not work 100% of times :)

We really should have something as easy 

FISX_DATA_DIR = od.getenv('FISX_DATA_DIR') or 'FISX_DATA_DIR_FROM_SETUP'

the env should get the precedence over everythings

**Comment by picca** [comment]
what about this

https://pyxdg.readthedocs.io/en/latest/basedirectory.html#data-directories

this is standard on unix.

**Comment by vasole** [comment]
Change line 34 from:

if not os.path.exists(FISX_DATA_DIR):

to:

if False:

And everything should work.

The first if block serves to nothing.

Armando

**Comment by picca** [comment]
ok removing the first block works.

now the only strange problem is during the installation of the package, the cython extension is rebuild once again ???

**Comment by vasole** [comment]
On 25.06.2016 18:09, picca wrote:

> ok removing the first block works.
> 
>  now the only strange problem is during the installation of the
> package, the cython extension is rebuild once again ???

Apparently it does not happen if one uses pip instead of python setup.py 
and a version of cython not adding the data and hour at the beginning of 
the generated files.

**Comment by picca** [comment]
> Apparently it does not happen if one uses pip instead of python setup.py
> and a version of cython not adding the data and hour at the beginning of
> the generated files.

not a big deal, I will upload the package now :)
