### ISSUE TITLE
warning during the Debian build process

### ISSUE THREAD

**Issue by picca** [vasole/fisx#16]
Hello, I put here the information gather during the build process.

running clean
removing '/<<PKGBUILDDIR>>/.pybuild/pythonX.Y-dbg_3.5/build' (and everything under it)
setup.py:90: ResourceWarning: unclosed file <_io.TextIOWrapper name='/<<PKGBUILDDIR>>/src/fisx_version.h' mode='r' encoding='ANSI_X3.4-1968'>
  content = open(os.path.join(cppDir, "fisx_version.h"), "r").readlines()
setup.py:237: ResourceWarning: unclosed file <_io.TextIOWrapper name='README.rst' mode='r' encoding='ANSI_X3.4-1968'>
  long_description = open("README.rst").read()

/<<PKGBUILDDIR>>/src/fisx_math.cpp: In static member function 'static double fisx::Math::hypermet(const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&, const double&)':
/<<PKGBUILDDIR>>/src/fisx_math.cpp:607:18: warning: unused variable 'MY_PI' [-Wunused-variable]
     const double MY_PI = 3.141592653589793;
                  ^
/<<PKGBUILDDIR>>/src/fisx_math.cpp:609:18: warning: unused variable 'log2' [-Wunused-variable]
     const double log2 = 0.69314718055994529;
                  ^
/<<PKGBUILDDIR>>/src/fisx_math.cpp:611:18: warning: unused variable 'sigmaToFWHM' [-Wunused-variable]
     const double sigmaToFWHM = 2.3548200450309493;
                  ^

/<<PKGBUILDDIR>>/src/fisx_xrf.cpp: In member function 'std::mapstd::__cxx11::basic_string<char, std::mapstd::__cxx11::basic_string<char, double> > fisx::XRF::getFluorescence(const string&, const fisx::Elements&, const int&, const string&, const int&, const int&)':
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:227:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (iLayer = 0; iLayer < sampleLayerIndex; iLayer++)
                             ^
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp: In member function 'double fisx::XRF::getGeometricEfficiency(const int&) const':
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:471:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (iLayer = referenceLayerIndex; iLayer < sampleLayerIndex; iLayer++)
                                                       ^
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:479:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (iLayer = sampleLayerIndex; iLayer < referenceLayerIndex; iLayer++)
                                                    ^
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp: In member function 'void fisx::XRF::getSpectrum(double_, double_, double*, int, const std::mapstd::__cxx11::basic_string<char, double>&, const std::mapstd::__cxx11::basic_string<char, double>&, const std::mapstd::__cxx11::basic_string<char, double>&, const expectedLayerEmissionType&) const':
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:594:12: warning: unused variable 'eta' [-Wunused-variable]
     double eta = 0.0;
            ^
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:630:33: warning: 'gain' may be used uninitialized in this function [-Wmaybe-uninitialized]
         energy[i] = zero + gain \* channel[i];
                                 ^
/<<PKGBUILDDIR>>/src/fisx_xrf.cpp:630:26: warning: 'zero' may be used uninitialized in this function [-Wmaybe-uninitialized]
         energy[i] = zero + gain \* channel[i];
                          ^

/<<PKGBUILDDIR>>/src/fisx_elements.cpp:1856:16: warning: variable 'factor' set but not used [-Wunused-but-set-variable]
         double factor;
                ^
/<<PKGBUILDDIR>>/src/fisx_elements.cpp:1831:12: warning: variable 'intrinsicEfficiency' set but not used [-Wunused-but-set-variable]
     double intrinsicEfficiency;
            ^
/<<PKGBUILDDIR>>/src/fisx_elements.cpp: In member function 'std::mapstd::__cxx11::basic_string<char, double> fisx::Elements::parseFormula(const string&) const':
/<<PKGBUILDDIR>>/src/fisx_elements.cpp:1635:13: warning: 'parsingKey' may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (parsingKey)
             ^

/<<PKGBUILDDIR>>/src/fisx_simpleini.cpp:94:17: warning: 'p0' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 if (p0 != 0)
                 ^
/<<PKGBUILDDIR>>/src/fisx_xrfconfig.cpp:68:10: warning: variable 'fisxFile' set but not used [-Wunused-but-set-variable]
     bool fisxFile;
          ^

/<<PKGBUILDDIR>>/src/fisx_epdl97.cpp:617:31: warning: unused variable 'j' [-Wunused-variable]
     int i, idx, iMu, nValues, j;
                               ^

**Comment by vasole** [comment]
Everything related to "hypermet" is unused code. I will get rid of it or fully implement it later on. It is functionality that I was hesitating between keeping it at PyMca level or at fisx level.

The possible use of uninitialized variables is more serious.
