### ISSUE TITLE
problem with fisx 0.1.0 during debian packaging

### ISSUE THREAD

**Issue by picca** [vasole/fisx#18]
Now I get this error.
# estSimpleSpecfileReadingWithCRLF (fisx.tests.testSimpleSpecfile.testSimpleSpecfile) ... ok
## ERROR: testXRFResults (fisx.tests.testXRF.testXRF)

Traceback (most recent call last):
  File "fisx/tests/testXRF.py", line 90, in testXRFResults
    elementsInstance.initializeAsPyMca()
  File "python/cython/_fisx.pyx", line 289, in fisx._fisx.PyElements.initializeAsPyMca (/<<PKGBUILDDIR>>/python/cython/_fisx.cpp:5358)
## AttributeError: 'fisx._fisx.PyElements' object has no attribute '__initializeAsPyMcaOld'

when I am looking at the code it seems now that fisx depends on pymca ????
pyma -> fisx -> pymca

all reference to Pymca should be removed from fisx and it should work without pymca

cheers

Frederic

**Comment by vasole** [comment]
fisx does not depend on PyMca but it can be initialized in the same way 
as PyMca.

**Comment by vasole** [comment]
It looks to me that you are running the fisx tests of latest version on 
a system with a previous fisx version installed.

**Comment by vasole** [comment]
Corrected. There was a mismatch in the naming of the internal method.

**Comment by picca** [comment]
could you upload 1.1.1 into pypi, in order to be able to package it :)

**Comment by vasole** [comment]
I need access to a Mac to generate the MacOS wheel and I will not have 
it till Monday.

**Comment by vasole** [comment]
@picca 

Version 1.1.1 uploaded to PyPI.

**Comment by picca** [comment]
uploaded :)
