### ISSUE TITLE
Syntax error in python/cython/_fisx.pyx

### ISSUE THREAD

**Issue by ddale** [vasole/fisx#2]
There appears to be a syntax error near https://github.com/vasole/fisx/blob/master/python/cython/_fisx.pyx#L733 :

``` python
def fisxVersion():
    return _fisxVersion()#import numpy as np
#cimport numpy as np
cimport cython
```

When I try to run setup.py on a unix system, I get:

```
cythoning /home/darren/conda-bld/work/python/cython/_fisx.pyx to /home/darren/conda-bld/work/python/cython/_fisx.cpp

Error compiling Cython file:
------------------------------------------------------------
...
#from libcpp.string cimport string as std_string

from Version cimport fisxVersion as _fisxVersion

def fisxVersion():
    return _fisxVersion()import numpy
                        ^
------------------------------------------------------------

python/cython/_fisx.pyx:93:25: Syntax error in simple statement list
```

I think the pyx file just needs to be changed to read:

``` python
def fisxVersion():
    return _fisxVersion()
#import numpy as np
#cimport numpy as np
cimport cython
```

however, making that change appears to have no effect on the build. Furthermore, running setup.py appears to rewrite _fisx.pyx in place, but I can't figure out why, or what source it is using to rewrite the contents of that file.

**Comment by ddale** [comment]
I found the problem. PyVersion.pyx is missing a newline character at the end of the file. I'll file a pull request.

(I wonder if _fisx.pyx and _fisx.cpp should be included in the git repo, since they are autogenerated. Just a thought.)

**Comment by vasole** [comment]
On 25.02.2015 21:30, Darren Dale wrote:

> I found the problem. PyVersion.pyx is missing a newline character at
> the end of the file. I'll file a pull request.
> 
> (I wonder if _fisx.pyx and _fisx.cpp should be included in the git
> repo, since they are autogenerated. Just a thought.)

The idea is to give the possibility to build the library to people 
without a recent version of cython.
