### ISSUE TITLE
Out of bounds array bug

### ISSUE THREAD

**Issue by tschoonj** [vasole/fisx#34]
Hi Armando,

I am seeing a compilation warning for the following two lines:

https://github.com/vasole/fisx/blob/c8373b80132132012a81d52eab0281169da157b3/src/fisx_math.cpp#L152-L153

```  
/tmp/pip-req-build-8m4M4E/src/fisx_math.cpp: In static member function ‘static double fisx::Math::AS_5_1_56(const double&)’:
/tmp/pip-req-build-8m4M4E/src/fisx_math.cpp:152:25: warning: array subscript is above array bounds [-Warray-bounds]
             num = (num + a[i]) * x;
                             ^
/tmp/pip-req-build-8m4M4E/src/fisx_math.cpp:153:25: warning: array subscript is above array bounds [-Warray-bounds]
             den = (den + b[i]) * x;
```

This looks like a bug to me as the first iteration will start at 4 causing therefore the out of bounds array access.

If you agree, I will gladly submit a PR with a fix.

Best,

Tom

**Comment by vasole** [comment]
Please, do so. It seems it should be a[i -1] and b[i -1] (or to change the loop limits)

**Comment by vasole** [comment]
Fortunately that function is never called. It is a left over from the initial development but it should be corrected. Thanks for the finding!

**Comment by tschoonj** [comment]
Yep I had a feeling it was never actually used as this easily might have led to a segfault or at the very least corrupted results.

**Comment by tschoonj** [comment]
Oh and by the way, I opened a request to have fisx [added](https://github.com/conda-forge/staged-recipes/pull/6699) to conda-forge.

When this one is merged in, I will create one for PyMca as well.

**Comment by vasole** [comment]
There is a conda.recipe for each of them fisx and PyMca. It was contributed y people using conda because I do not use it.

**Comment by tschoonj** [comment]
I know but they are all outdated and conda-forge makes the platform specific builds using CI/CD, which is the hard part... and they do it in such a way that the resulting binaries will run on some pretty old version of Linux and macOS.

I will let you know when the whole process is complete, in case you want to announce it on the mailinglist or so... I am sure some of your users may find it interesting to know.

**Comment by vasole** [comment]
Please, feel free to update the recipes of fisx and PyMca of their respective repositories if that helps.

I prefer to have them removed than to have them wrong.

**Comment by tschoonj** [comment]
That's impossible I am afraid as they all appear to be in personal repositories (e.g. Nicola Vigano). I have no control over them.

This is why I prefer conda-forge as I would not be the only maintainer and is a known source for trustworthy packages.

**Comment by vasole** [comment]
I meant those found in the repository under conda.recipes  For instance, the one of fisx is:

https://github.com/vasole/fisx/tree/master/conda.recipe

**Comment by tschoonj** [comment]
ok thanks for the clarification

I will remove them when both fisx and PyMca have made it onto conda-forge.
