### ISSUE TITLE
duplicates/out-of-sync _fisx.cpp

### ISSUE THREAD

**Issue by newville** [vasole/fisx#5]
`python/cython/_fisx.cpp` is included in the git tree but appears to be over-written each time `python setup.py build` is run.   If it is always built (should it be, or only when needed?), it should not be part of the source control system.

**Comment by vasole** [comment]
The goal is to allow to build the library if cython is not installed or if the cython version is too old.

**Comment by newville** [comment]
But that means that simply building from source makes the source code repository no longer in-sync with the master branch.  

You could _copy_ this source file from somewhere else if a suitable version of Cython is not available, but automatically overwriting a file in the source repository is a very bad idea.

In fact, it appears that the Cython step happens with every `python setup.py`, which then causes the whole compilation.  That is really annoying.  Please fix so it compiles when needed, but not otherwise.

**Comment by vasole** [comment]
Please, review the changes to see if there are more things to be corrected.

**Comment by vasole** [comment]
Travis (on linux and Mac) and Appveyor (windows) tests pass.
